language: python
python:
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6"
before_install:
        - chmod +x run_build.sh
install:
        - pip install -r requirements.txt
script: ./run_build.sh
